apiVersion: v1
kind: Service
metadata:
  name: cap10-visits-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: visits-app
  selector:
    app: visits
  type: NodePort
