kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: naomi-core-apps
subjects:
- kind: User
  name: naomi
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cap09-clusterrole-core-apps
  apiGroup: rbac.authorization.k8s.io

