kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cap09-sa-lector-pods-listar-pods
subjects:
- kind: ServiceAccount
  name: sa-lector-pods
roleRef:
  kind: Role
  name: cap09-listar-pods
  apiGroup: rbac.authorization.k8s.io

