kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cap09-marcos-impersonator
subjects:
- kind: User
  name: marcos
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cap09-impersonator
  apiGroup: rbac.authorization.k8s.io

