apiVersion: v1
kind: Pod
metadata:
  name: ape02-pod-secreto
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: USERNAME
        valueFrom: 
          secretKeyRef:
            key: username
            name: ape02-secret
      - name: PASSWORD
        valueFrom: 
          secretKeyRef:
            key: password
            name: ape02-secret
