apiVersion: v1
kind: Pod
metadata:
  name: cap11-apprunasuser-group
spec:
  containers:
  - image: app
    name: cap11-apprunasuser-group
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
