apiVersion: v1
kind: Pod
metadata:
  name: cap11-appnonroot
spec:
  containers:
  - image: app
    name: cap11-appnonroot
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    securityContext:
      runAsNonRoot: true
