apiVersion: v1
kind: Pod
metadata:
  name: cap11-appnoescalation
spec:
  containers:
  - image: appsudo
    name: cap11-appnoescalation
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
