FROM python:3.8

RUN apt update && apt install -y sudo && \
    groupadd -g 1000 appgrp && \
    useradd -g 1000 -l -m -u 1000 appuser && \
    echo 'appuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers 

USER 1000

EXPOSE 8000

ENTRYPOINT ["python3", "-m", "http.server"]

