apiVersion: v1
kind: Pod
metadata:
  name: demoapp-node-anti-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu
            operator: DoesNotExist
  containers:
  - name: demoapp-node-anti-affinity
    image: tuxotron/demoapp:v1

