apiVersion: v1
kind: Pod
metadata:
  name: demoapp-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: run
            operator: In
            values:
            - redis
        topologyKey: kubernetes.io/hostname
  containers:
  - name: demoapp-pod-affinity
    image: tuxotron/demoapp:v1

