apiVersion: v1
kind: Pod
metadata:
  name: demoapp-node-preferred-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: gpu
            operator: In
            values:
            - nvidia
      - weight: 50
        preference:
          matchExpressions:
          - key: disco
            operator: In
            values:
            - ssd
  containers:
  - name: demoapp-node-preferred-affinity
    image: tuxotron/demoapp:v1

