apiVersion: v1
kind: Pod
metadata:
  name: cap06-configmap-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: DB_IP
        valueFrom: 
          configMapKeyRef:
            key: db_ip
            name: cap06-configmap
      - name: LANG
        valueFrom: 
          configMapKeyRef:
            key: lang
            name: cap06-configmap          
