apiVersion: v1
kind: Pod
metadata:
  name: cap06-opaque-secret-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: USERNAME
        valueFrom: 
          secretKeyRef:
            key: username
            name: cap06-opaque-secret
      - name: PASSWORD
        valueFrom: 
          secretKeyRef:
            key: password
            name: cap06-opaque-secret
