apiVersion: v1
kind: Pod
metadata:
  name: cap06-opaque-secret-pod-vol
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: cap06-opaque-secret-vol
        mountPath: /mysecrets
  volumes:
    - name: cap06-opaque-secret-vol
      secret:
        secretName: cap06-opaque-secret
