apiVersion: v1
kind: Pod
metadata:
  name: cap06-configmap-pod-vol
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: cap06-configmap-vol
        mountPath: /myconfig
  volumes:
    - name: cap06-configmap-vol
      configMap:
        name: cap06-configmap
