apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-example
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
      - name: MYVAR
        value: myvalue
      - name: MYUSERNAME
        valueFrom: 
          secretKeyRef:
            key: username
            name: demoapp-secret
          
    volumeMounts:
      - name: demoapp-secret-vol
        mountPath: /mysecret
  volumes:
    - name: demoapp-secret-vol
      secret:
        secretName: demoapp-secret
