apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cap08-demoapp
spec:
  selector:
    matchLabels:
      app: cap08-demoapp-stateful
  serviceName: "cap08-demoapp-stateful-service"
  volumeClaimTemplates:
  - metadata:
      name: cap08-sts-pvc
    spec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  template:
    metadata:
      labels:
        app: cap08-demoapp-stateful
    spec:
      containers:
      - name: demoapp
        image: tuxotron/demoapp:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: cap08-sts-pvc
          mountPath: /data

