apiVersion: v1
kind: Pod
metadata:
  name: init-container-example-error
spec:
  initContainers:
    - name: init
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
      - exit 1
        
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
      - containerPort: 80

