apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    etiqueta: valor
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
      - name: MYVAR
        value: myvalue