apiVersion: v1
kind: Pod
metadata:
  name: pod-cpu-request
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources:
      requests:
        cpu: "1100m"
