apiVersion: v1
kind: Pod
metadata:
  name: pod-restart
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    restartPolicy: Always
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
