apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demoapp-stateful
spec:
  selector:
    matchLabels:
      app: demoapp-stateful
  serviceName: "demoapp-stateful-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: demoapp-stateful
    spec:
      containers:
      - name: demoapp
        image: tuxotron/demoapp:v2
        ports:
        - containerPort: 8080
