apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap05-deployment
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 2
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: tuxotron/demoapp:v1
        ports:
        - containerPort: 8080
