apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap05-deployment
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demoapp
      annotations:
        kubernetes.io/change-cause: "Update v3"
    spec:
      containers:
      - name: demoapp
        image: tuxotron/demoapp:v3
        ports:
        - containerPort: 8080
