apiVersion: batch/v1
kind: Job
metadata:
  name: backoff-onfailure
spec:
  backoffLimit: 4
  template:
    metadata:
      name: backoff-onfailure
    spec:
      containers:
      - name: error
        image: busybox
        command:
         - "/bin/sh"
         - "-c"
         - "sleep 2; exit -1"
      restartPolicy: OnFailure
