apiVersion: v1
kind: Service
metadata:
  name: demoapp-stateful-service
  labels:
    app: demoapp-stateful
spec:
  ports:
  - port: 80
    targetPort: 8080
  clusterIP: None
  selector:
    app: demoapp-stateful
