apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-parallel
spec:
  parallelism: 4
  template:
    metadata:
      name: countdown-parallel
    spec:
      containers:
      - name: counter
        image: busybox
        command:
         - "/bin/sh"
         - "-c"
         - "sleep 5 ; for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never
