apiVersion: batch/v1
kind: CronJob
metadata:
  name: cj-countdown
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: cj-countdown
        spec:
          containers:
          - name: counter
            image: busybox
            command:
            - "/bin/sh"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
          restartPolicy: Never
